resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/17.yaml

packages:
- xmobar

extra-deps:
- netlink-1.1.1.0
- cairo-0.13.8.2
- pango-0.13.8.2
- glib-0.13.8.2

flags:
  xmobar:
    all_extensions: true
