POWERLEVEL9K_MODE="nerdfont-complete"
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%B%(?:%F{green}:%F{red})  ➜ %f"

typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[alias]='fg=10,bold' # 10=lightgreen
ZSH_HIGHLIGHT_STYLES[function]='fg=10,bold' # 10=lightgreen
ZSH_HIGHLIGHT_STYLES[path]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=magenta,underline'
ZSH_HIGHLIGHT_STYLES[arithmetic-expansion]='fg=yellow,underline'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=cyan'

typeset -A ZSH_HIGHLIGHT_PRECOMMANDS
ZSH_HIGHLIGHT_PRECOMMANDS=(
  each ''
)

if [[ -z "$TERMUX_VERSION" ]]; then
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon status context dir vcs)
else
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_android_icon status context dir vcs)
fi
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_HIDE_SIGNAME=false
## Contect Segment ##
  POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND=61
  POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=61
  POWERLEVEL9K_CONTEXT_SUDO_BACKGROUND=61
  POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND=61
  POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND=61

  POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=15
  POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=15
  POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND=15
  POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=15
  POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND=15

## Segment Path
  POWERLEVEL9K_DIR_HOME_BACKGROUND=1
  POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND=1
  POWERLEVEL9K_DIR_ETC_BACKGROUND=1
  POWERLEVEL9K_DIR_DEFAULT_BACKGROUND=1

  POWERLEVEL9K_DIR_HOME_FOREGROUND=0
  POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND=0
  POWERLEVEL9K_DIR_ETC_FOREGROUND=0
  POWERLEVEL9K_DIR_DEFAULT_FOREGROUND=0

  POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
  POWERLEVEL9K_SHORTEN_DELIMITER=".."
  POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"

  ## OS icon ##
  if [[ "$HOST" == "tuxcord.net" ]]; then
    POWERLEVEL9K_LINUX_ICON=$'\uF31D'
    POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION="$POWERLEVEL9K_LINUX_ICON"
    POWERLEVEL9K_OS_ICON_FOREGROUND=203
    POWERLEVEL9K_OS_ICON_BACKGROUND=235
  else
    POWERLEVEL9K_LINUX_ICON=$'\uF31F'
    POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION="$POWERLEVEL9K_LINUX_ICON"
    POWERLEVEL9K_OS_ICON_FOREGROUND=81
    POWERLEVEL9K_OS_ICON_BACKGROUND=235
  fi
  ## Android OS icon ##
  # TODO: check on pl10k
  POWERLEVEL9K_CUSTOM_ANDROID_ICON="echo ﲎ"
  POWERLEVEL9K_CUSTOM_ANDROID_ICON_FOREGROUND=64
  POWERLEVEL9K_CUSTOM_ANDROID_ICON_BACKGROUND=15
