#!/bin/bash

xxdp() {
    xxd -R always "$@" | "${PAGER:-less}"
}

touchp() {
  while [ "$#" -gt 0 ]; do
    mkdir -p "$(dirname "$1")"
    touch "$1"
    shift
  done
}

# TODO: I think I would still use a command that pops directory contents in one
# go.
# popdir() {
#   [...]
# }

copyf() {
    $CLIP_COPY < "$1" # CLIP_COPY spread intentional
}

cdp() {
    # shellcheck disable=SC2164
    mkdir -p "$1" && cd "$1"
}

egpg() {
    FILE_PATH=$(mktemp -t "egpg.XXXXXX")
    $EDITOR "$FILE_PATH" # EDITOR spread intentional
    gpg "$@" < "$FILE_PATH"
    rm -f "$FILE_PATH"
}

each() {
    while read -r ln; do
        "$@" "$ln"
    done
}

y() {
    local tmp
    tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
    command yazi "$@" --cwd-file="$tmp"
    IFS= read -r -d '' cwd < "$tmp"
    [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd" || :
    rm -f -- "$tmp"
}

# should do the thing of showing a file in the file explorer (cd into dirname
# and highlight such file), but its quite frail
show() {
    dbus-send --session \
        --dest=org.freedesktop.FileManager1 \
        --type=method_call \
        /org/freedesktop/FileManager1 \
        org.freedesktop.FileManager1.ShowItems \
        array:string:"file://$(realpath "$1")" \
        string:""
}

man() {
    command man "$@" | bat -pl man
}

man1() {
    command man "$1" | bat -pl man
}
