input {
    follow_mouse = 2
    float_switch_override_focus = 0

    kb_layout = es
    repeat_rate = 35
    repeat_delay = 200

    touchpad {
        natural_scroll = true
        disable_while_typing = false
        # middle_button_emulation = true
        drag_3fg = 1
    }
}

ecosystem {
    no_update_news = true
}

dwindle {
    # thing is, I do love this when I'm with several windows or when I put the
    # cursor on the edge of the screen, BUT usually i just want new windows to
    # show on my left/right side when im in single window and my cursor never
    # in a position for that.
    #
    # I'd love to see this but if your cursor is a window insted of a gap it
    # places the new window vertically splitting that window, not with the
    # relative pos or whatever
    #
    # smart_split = true
}


windowrule = match:class steam_app.*, match:xwayland true, no_anim true

windowrule = match:title Save file, match:class com\.rtosta\.zapzap, float true

windowrule = match:title Layer Select, match:class gimp, float true
windowrule = match:title Export Image as .*, match:class file-.*, float true

windowrule = match:class .*-float, float true, size 960 540, center true
